// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WemerMultiPageWebAppDb.Models;

namespace WemerMultiPageWebAppDb.Migrations
{
    [DbContext(typeof(ContactsContext))]
    [Migration("20210210170402_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WemerMultiPageWebAppDb.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Adress = "201 Hazel Street Van Meter Iowa 50261",
                            Name = "Glenn",
                            Note = "Dad",
                            PhoneNumber = "(515)-210-8346"
                        },
                        new
                        {
                            ContactId = 2,
                            Adress = "201 Hazel Street Van Meter Iowa 50261",
                            Name = "Colby",
                            Note = "Me",
                            PhoneNumber = "(515)-478-4955"
                        },
                        new
                        {
                            ContactId = 3,
                            Adress = "201 Hazel Street Van Meter Iowa 50261",
                            Name = "kim",
                            Note = "Mom",
                            PhoneNumber = "(515)-210-8347"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
